#!/usr/bin/env bash
# index.sh — Regenerate INDEX.md (current year) and archive/YYYY.md (past years)
# Usage: ./scripts/index.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX_FILE="$REPO_ROOT/INDEX.md"
POCS_DIR="$REPO_ROOT/pocs"
ARCHIVE_DIR="$REPO_ROOT/archive"
DOCS_DIR="$REPO_ROOT/docs"
CURRENT_YEAR=$(date +%Y)
TMPDIR_ROWS=$(mktemp -d)
TMPDIR_JSON=$(mktemp -d)
trap 'rm -rf "$TMPDIR_ROWS" "$TMPDIR_JSON"' EXIT

mkdir -p "$ARCHIVE_DIR" "$DOCS_DIR"

extract_field() {
  grep -i "^[|] \*\*${2}\*\*" "$1" 2>/dev/null \
    | head -1 \
    | sed 's/.*| \*\*[^*]*\*\* | //' \
    | sed 's/ |.*//' \
    | sed 's/<!--.*-->//g' \
    | xargs
}

extract_summary() {
  python3 - "$1" <<'PYEOF'
import sys, re
try:
    content = open(sys.argv[1], encoding='utf-8', errors='replace').read()
    if '## Summary' not in content:
        print('')
        sys.exit(0)
    section = content.split('## Summary', 1)[1].split('\n## ', 1)[0]
    section = re.sub(r'<!--.*?-->', '', section, flags=re.DOTALL)
    for line in section.split('\n'):
        line = line.strip()
        if line and not line.startswith('#') and not line.startswith('|') and not line.startswith('-'):
            out = line[:280].replace('\\', '\\\\').replace('"', '\\"')
            print(out)
            break
except Exception:
    print('')
PYEOF
}

tags_to_json_array() {
  python3 -c "
import sys, json
t = sys.stdin.read().strip()
arr = [x.strip() for x in t.split(',') if x.strip()]
print(json.dumps(arr, ensure_ascii=False))
" <<< "$1"
}

total=0

while IFS= read -r -d '' readme; do
  rel="${readme#$POCS_DIR/}"
  category=$(echo "$rel" | cut -d'/' -f1)

  date_added=$(extract_field "$readme" "Date Added")
  last_updated=$(extract_field "$readme" "Last Updated" || true)
  cve=$(extract_field "$readme" "CVE / Advisory")
  severity=$(extract_field "$readme" "Severity")
  cvss=$(extract_field "$readme" "CVSS Score")
  tags=$(extract_field "$readme" "Tags")
  status=$(extract_field "$readme" "Status")
  summary=$(extract_summary "$readme")

  folder=$(dirname "$readme")
  name=$(basename "$folder")
  display_name=$(echo "$name" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_//')
  rel_path="${readme#$REPO_ROOT/}"
  rel_dir=$(dirname "$rel_path")

  row="| ${date_added:-—} | ${last_updated:-—} | [${display_name}](./${rel_dir}/) | \`${category}\` | ${cve:-N/A} | ${severity:-—} | ${tags:-—} | ${status:-—} |"

  # Group by CVE year; fall back to Date Added year if no CVE
  cve_year=$(echo "$cve" | grep -oP 'CVE-\K[0-9]{4}' | head -1 || true)
  if [[ -n "$cve_year" && "$cve_year" =~ ^[0-9]{4}$ ]]; then
    year="$cve_year"
  else
    year=$(echo "$date_added" | cut -d'-' -f1)
    [[ -z "$year" || ! "$year" =~ ^[0-9]{4}$ ]] && year="unknown"
  fi

  echo "$row" >> "$TMPDIR_ROWS/${year}.rows"

  # Escape strings for JSON
  json_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g;s/"/\\"/g'; }
  rel_dir_from_root="${readme#$REPO_ROOT/}"
  poc_url="$(dirname "$rel_dir_from_root")/"
  tags_json=$(tags_to_json_array "${tags:-}")

  printf '  {\n    "date": "%s",\n    "updated": "%s",\n    "name": "%s",\n    "category": "%s",\n    "cve": "%s",\n    "cvss": "%s",\n    "severity": "%s",\n    "tags": %s,\n    "summary": "%s",\n    "status": "%s",\n    "cve_year": "%s",\n    "url": "%s"\n  }' \
    "$(json_escape "${date_added:-}")" \
    "$(json_escape "${last_updated:-}")" \
    "$(json_escape "${display_name}")" \
    "$(json_escape "${category}")" \
    "$(json_escape "${cve:-N/A}")" \
    "$(json_escape "${cvss:-}")" \
    "$(json_escape "${severity:-}")" \
    "${tags_json}" \
    "$(json_escape "${summary:-}")" \
    "$(json_escape "${status:-}")" \
    "$(json_escape "${year}")" \
    "$(json_escape "${poc_url}")" \
    >> "$TMPDIR_JSON/entries.json"
  echo "," >> "$TMPDIR_JSON/entries.json"

  total=$((total + 1))
done < <(find "$POCS_DIR" -mindepth 3 -maxdepth 3 -name "README.md" -print0 | sort -z)

# Write archive files for past years
if compgen -G "$TMPDIR_ROWS/*.rows" > /dev/null 2>&1; then
  for rows_file in "$TMPDIR_ROWS"/*.rows; do
    [[ -f "$rows_file" ]] || continue
    year=$(basename "$rows_file" .rows)
    [[ "$year" == "$CURRENT_YEAR" ]] && continue

    count=$(wc -l < "$rows_file" | xargs)
    {
      echo "# POC Archive — ${year}"
      echo ""
      echo "> Auto-generated by \`scripts/index.sh\`. Do not edit manually."
      echo ""
      echo "---"
      echo ""
      echo "| Date Added | Last Updated | Name | Category | CVE | Severity | Tags | Status |"
      echo "|---|---|---|---|---|---|---|---|"
      cat "$rows_file"
      echo ""
      echo "---"
      echo ""
      echo "*Total: ${count} POC(s)*"
    } > "$ARCHIVE_DIR/${year}.md"
  done
fi

# Write INDEX.md
{
  echo "# POC Archive — Index"
  echo ""
  echo "> Last updated: $(date "+%Y-%m-%d %H:%M:%S")"
  echo ""
  echo "---"
  echo ""
  echo "## ${CURRENT_YEAR}"
  echo ""
  echo "| Date Added | Last Updated | Name | Category | CVE | Severity | Tags | Status |"
  echo "|---|---|---|---|---|---|---|---|"

  if [[ -f "$TMPDIR_ROWS/${CURRENT_YEAR}.rows" ]]; then
    cat "$TMPDIR_ROWS/${CURRENT_YEAR}.rows"
  fi

  echo ""
  echo "---"
  echo ""
  echo "*Total POCs: ${total}*"
  echo ""
  echo "## By Category"
  echo ""

  for cat_dir in "$POCS_DIR"/*/; do
    cat_name=$(basename "$cat_dir")
    cat_count=$(find "$cat_dir" -name "README.md" 2>/dev/null | wc -l | xargs)
    echo "- **\`${cat_name}\`** — ${cat_count} entries"
  done

  # Links to past year archives
  if compgen -G "$ARCHIVE_DIR/*.md" > /dev/null 2>&1; then
    echo ""
    echo "## Archives"
    echo ""
    for f in $(ls "$ARCHIVE_DIR"/*.md | sort -r); do
      [[ "$(basename "$f")" == ".gitkeep" ]] && continue
      year=$(basename "$f" .md)
      count=0
      [[ -f "$TMPDIR_ROWS/${year}.rows" ]] && count=$(wc -l < "$TMPDIR_ROWS/${year}.rows" | xargs)
      echo "- [${year}](./archive/${year}.md) — ${count} entries"
    done
  fi

  echo ""
} > "$INDEX_FILE"

# Write docs/data.json
{
  echo "{"
  printf '  "generated": "%s",\n' "$(date "+%Y-%m-%d %H:%M:%S")"
  printf '  "total": %d,\n' "$total"
  echo '  "pocs": ['
  if [[ -f "$TMPDIR_JSON/entries.json" ]]; then
    # Remove trailing comma from last entry
    sed '$ s/,$//' "$TMPDIR_JSON/entries.json"
  fi
  echo '  ]'
  echo '}'
} > "$DOCS_DIR/data.json"

echo "INDEX.md + data.json updated — ${total} POC(s) indexed."
