#!/usr/bin/env bash
# index.sh — Scan all POC entries and regenerate INDEX.md
# Usage: ./scripts/index.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX_FILE="$REPO_ROOT/INDEX.md"
POCS_DIR="$REPO_ROOT/pocs"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Scanning POC entries...${NC}"

# --- Header ---
cat > "$INDEX_FILE" << 'HEADER'
# POC Archive — Index

> Auto-generated by `scripts/index.sh`. Do not edit manually.
> Last updated: TIMESTAMP

---

## Full Index

| Date | Name | Category | CVE | Severity | Tags | Status |
|---|---|---|---|---|---|---|
HEADER

# Replace TIMESTAMP placeholder
today=$(date "+%Y-%m-%d %H:%M:%S")
if sed --version 2>/dev/null | grep -q GNU; then
  sed -i "s/TIMESTAMP/${today}/" "$INDEX_FILE"
else
  sed -i '' "s/TIMESTAMP/${today}/" "$INDEX_FILE"
fi

# --- Scan all README.md files in pocs/ ---
count=0

while IFS= read -r -d '' readme; do
  # Extract category from path
  rel="${readme#$POCS_DIR/}"
  category=$(echo "$rel" | cut -d'/' -f1)

  # Extract fields from markdown metadata table
  extract_field() {
    grep -i "^\| \*\*${1}\*\*" "$readme" 2>/dev/null \
      | head -1 \
      | sed 's/.*| \*\*[^*]*\*\* | //' \
      | sed 's/ |.*//' \
      | sed 's/<!--.*-->//g' \
      | xargs
  }

  date_added=$(extract_field "Date Added")
  cve=$(extract_field "CVE / Advisory")
  severity=$(extract_field "Severity")
  tags=$(extract_field "Tags")
  status=$(extract_field "Status")

  # Get name from folder
  folder=$(dirname "$readme")
  name=$(basename "$folder")
  # Strip date prefix if present (YYYY-MM-DD_name → name)
  display_name=$(echo "$name" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_//')

  # Build relative link
  rel_path="${readme#$REPO_ROOT/}"
  rel_dir=$(dirname "$rel_path")

  echo "| ${date_added:-—} | [${display_name}](./${rel_dir}/) | \`${category}\` | ${cve:-N/A} | ${severity:-—} | ${tags:-—} | ${status:-—} |" >> "$INDEX_FILE"

  count=$((count + 1))
done < <(find "$POCS_DIR" -name "README.md" -not -path "*/node_modules/*" -print0 | sort -z)

# --- Footer ---
cat >> "$INDEX_FILE" << FOOTER

---

*Total POCs: ${count}*

## By Category

FOOTER

# Category breakdown
for cat_dir in "$POCS_DIR"/*/; do
  cat_name=$(basename "$cat_dir")
  cat_count=$(find "$cat_dir" -name "README.md" 2>/dev/null | wc -l | xargs)
  echo "- **\`${cat_name}\`** — ${cat_count} entries" >> "$INDEX_FILE"
done

echo "" >> "$INDEX_FILE"

echo -e "${GREEN}✅ INDEX.md updated — ${count} POC(s) indexed.${NC}"
